[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
log = "0.4.22"
env_logger = "0.11.5"
